# Generated by Django 5.1.2 on 2024-10-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
